INSERT INTO countries SET language_id=3, name="Afghanistan", alternative_spellings="AF افغانستان";
INSERT INTO countries SET language_id=3, name="Åland Islands", alternative_spellings="AX Aaland Aland", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Albania", alternative_spellings="AL";
INSERT INTO countries SET language_id=3, name="Algeria", alternative_spellings="DZ الجزائر";
INSERT INTO countries SET language_id=3, name="American Samoa", alternative_spellings="AS", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Andorra", alternative_spellings="AD", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Angola", alternative_spellings="AO";
INSERT INTO countries SET language_id=3, name="Anguilla", alternative_spellings="AI", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Antarctica", alternative_spellings="AQ", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Antigua And Barbuda", alternative_spellings="AG", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Argentina", alternative_spellings="AR";
INSERT INTO countries SET language_id=3, name="Armenia", alternative_spellings="AM Հայաստան";
INSERT INTO countries SET language_id=3, name="Aruba", alternative_spellings="AW", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Australia", alternative_spellings="AU", relevancy="5";
INSERT INTO countries SET language_id=3, name="Austria", alternative_spellings="AT Österreich Osterreich Oesterreich ";
INSERT INTO countries SET language_id=3, name="Azerbaijan", alternative_spellings="AZ";
INSERT INTO countries SET language_id=3, name="Bahamas", alternative_spellings="BS";
INSERT INTO countries SET language_id=3, name="Bahrain", alternative_spellings="BH البحرين";
INSERT INTO countries SET language_id=3, name="Bangladesh", alternative_spellings="BD বাংলাদেশ", relevancy="2";
INSERT INTO countries SET language_id=3, name="Barbados", alternative_spellings="BB";
INSERT INTO countries SET language_id=3, name="Belarus", alternative_spellings="BY Беларусь";
INSERT INTO countries SET language_id=3, name="Belgium", alternative_spellings="BE België Belgie Belgien Belgique", relevancy="5";
INSERT INTO countries SET language_id=3, name="Belize", alternative_spellings="BZ";
INSERT INTO countries SET language_id=3, name="Benin", alternative_spellings="BJ";
INSERT INTO countries SET language_id=3, name="Bermuda", alternative_spellings="BM", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Bhutan", alternative_spellings="BT भूटान";
INSERT INTO countries SET language_id=3, name="Bolivia", alternative_spellings="BO";
INSERT INTO countries SET language_id=3, name="Bonaire, Sint Eustatius and Saba", alternative_spellings="BQ";
INSERT INTO countries SET language_id=3, name="Bosnia and Herzegovina", alternative_spellings="BA Босна и Херцеговина";
INSERT INTO countries SET language_id=3, name="Botswana", alternative_spellings="BW";
INSERT INTO countries SET language_id=3, name="Bouvet Island", alternative_spellings="BV";
INSERT INTO countries SET language_id=3, name="Brazil", alternative_spellings="BR Brasil", relevancy="2";
INSERT INTO countries SET language_id=3, name="British Indian Ocean Territory", alternative_spellings="IO";
INSERT INTO countries SET language_id=3, name="Brunei Darussalam", alternative_spellings="BN";
INSERT INTO countries SET language_id=3, name="Bulgaria", alternative_spellings="BG България";
INSERT INTO countries SET language_id=3, name="Burkina Faso", alternative_spellings="BF";
INSERT INTO countries SET language_id=3, name="Burundi", alternative_spellings="BI";
INSERT INTO countries SET language_id=3, name="Cambodia", alternative_spellings="KH កម្ពុជា";
INSERT INTO countries SET language_id=3, name="Cameroon", alternative_spellings="CM";
INSERT INTO countries SET language_id=3, name="Canada", alternative_spellings="CA", relevancy="5";
INSERT INTO countries SET language_id=3, name="Cape Verde", alternative_spellings="CV Cabo";
INSERT INTO countries SET language_id=3, name="Cayman Islands", alternative_spellings="KY", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Central African Republic", alternative_spellings="CF";
INSERT INTO countries SET language_id=3, name="Chad", alternative_spellings="TD تشاد‎ Tchad";
INSERT INTO countries SET language_id=3, name="Chile", alternative_spellings="CL";
INSERT INTO countries SET language_id=3, name="China", relevancy="3.5", alternative_spellings="CN Zhongguo Zhonghua Peoples Republic 中国/中华";
INSERT INTO countries SET language_id=3, name="Christmas Island", alternative_spellings="CX", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Cocos (Keeling) Islands", alternative_spellings="CC", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Colombia", alternative_spellings="CO";
INSERT INTO countries SET language_id=3, name="Comoros", alternative_spellings="KM جزر القمر";
INSERT INTO countries SET language_id=3, name="Congo", alternative_spellings="CG";
INSERT INTO countries SET language_id=3, name="Congo, the Democratic Republic of the", alternative_spellings="CD Congo-Brazzaville Repubilika ya Kongo";
INSERT INTO countries SET language_id=3, name="Cook Islands", alternative_spellings="CK", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Costa Rica", alternative_spellings="CR";
INSERT INTO countries SET language_id=3, name="Côte d\'Ivoire", alternative_spellings="CI Cote dIvoire";
INSERT INTO countries SET language_id=3, name="Croatia", alternative_spellings="HR Hrvatska";
INSERT INTO countries SET language_id=3, name="Cuba", alternative_spellings="CU";
INSERT INTO countries SET language_id=3, name="Curaçao", alternative_spellings="CW Curacao";
INSERT INTO countries SET language_id=3, name="Cyprus", alternative_spellings="CY Κύπρος Kýpros Kıbrıs";
INSERT INTO countries SET language_id=3, name="Czech Republic", alternative_spellings="CZ Česká Ceska";
INSERT INTO countries SET language_id=3, name="Denmark", alternative_spellings="DK Danmark", relevancy="5";
INSERT INTO countries SET language_id=3, name="Djibouti", alternative_spellings="DJ جيبوتي‎ Jabuuti Gabuuti";
INSERT INTO countries SET language_id=3, name="Dominica", alternative_spellings="DM Dominique", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Dominican Republic", alternative_spellings="DO";
INSERT INTO countries SET language_id=3, name="Ecuador", alternative_spellings="EC";
INSERT INTO countries SET language_id=3, name="Egypt", alternative_spellings="EG", relevancy="1.5";
INSERT INTO countries SET language_id=3, name="El Salvador", alternative_spellings="SV";
INSERT INTO countries SET language_id=3, name="Equatorial Guinea", alternative_spellings="GQ";
INSERT INTO countries SET language_id=3, name="Eritrea", alternative_spellings="ER إرتريا ኤርትራ";
INSERT INTO countries SET language_id=3, name="Estonia", alternative_spellings="EE Eesti";
INSERT INTO countries SET language_id=3, name="Ethiopia", alternative_spellings="ET ኢትዮጵያ";
INSERT INTO countries SET language_id=3, name="Falkland Islands (Malvinas)", alternative_spellings="FK", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Faroe Islands", alternative_spellings="FO Føroyar Færøerne", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Fiji", alternative_spellings="FJ Viti फ़िजी";
INSERT INTO countries SET language_id=3, name="Finland", alternative_spellings="FI Suomi";
INSERT INTO countries SET language_id=3, name="France", alternative_spellings="FR République française", relevancy="3.5";
INSERT INTO countries SET language_id=3, name="French Guiana", alternative_spellings="GF";
INSERT INTO countries SET language_id=3, name="French Polynesia", alternative_spellings="PF Polynésie française";
INSERT INTO countries SET language_id=3, name="French Southern Territories", alternative_spellings="TF";
INSERT INTO countries SET language_id=3, name="Gabon", alternative_spellings="GA République Gabonaise";
INSERT INTO countries SET language_id=3, name="Gambia", alternative_spellings="GM";
INSERT INTO countries SET language_id=3, name="Georgia", alternative_spellings="GE საქართველო";
INSERT INTO countries SET language_id=3, name="Germany", alternative_spellings="DE Bundesrepublik Deutschland", relevancy="5";
INSERT INTO countries SET language_id=3, name="Ghana", alternative_spellings="GH";
INSERT INTO countries SET language_id=3, name="Gibraltar", alternative_spellings="GI", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Greece", alternative_spellings="GR Ελλάδα", relevancy="1.5";
INSERT INTO countries SET language_id=3, name="Greenland", alternative_spellings="GL grønland", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Grenada", alternative_spellings="GD";
INSERT INTO countries SET language_id=3, name="Guadeloupe", alternative_spellings="GP";
INSERT INTO countries SET language_id=3, name="Guam", alternative_spellings="GU";
INSERT INTO countries SET language_id=3, name="Guatemala", alternative_spellings="GT";
INSERT INTO countries SET language_id=3, name="Guernsey", alternative_spellings="GG", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Guinea", alternative_spellings="GN";
INSERT INTO countries SET language_id=3, name="Guinea-Bissau", alternative_spellings="GW";
INSERT INTO countries SET language_id=3, name="Guyana", alternative_spellings="GY";
INSERT INTO countries SET language_id=3, name="Haiti", alternative_spellings="HT";
INSERT INTO countries SET language_id=3, name="Heard Island and McDonald Islands", alternative_spellings="HM";
INSERT INTO countries SET language_id=3, name="Holy See (Vatican City State)", alternative_spellings="VA", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Honduras", alternative_spellings="HN";
INSERT INTO countries SET language_id=3, name="Hong Kong", alternative_spellings="HK 香港";
INSERT INTO countries SET language_id=3, name="Hungary", alternative_spellings="HU Magyarország";
INSERT INTO countries SET language_id=3, name="Iceland", alternative_spellings="IS Island";
INSERT INTO countries SET language_id=3, name="India", alternative_spellings="IN भारत गणराज्य Hindustan", relevancy="3";
INSERT INTO countries SET language_id=3, name="Indonesia", alternative_spellings="ID", relevancy="2";
INSERT INTO countries SET language_id=3, name="Iran, Islamic Republic of", alternative_spellings="IR ایران";
INSERT INTO countries SET language_id=3, name="Iraq", alternative_spellings="IQ العراق‎";
INSERT INTO countries SET language_id=3, name="Ireland", alternative_spellings="IE Éire", relevancy="5";
INSERT INTO countries SET language_id=3, name="Isle of Man", alternative_spellings="IM", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Israel", alternative_spellings="IL إسرائيل ישראל";
INSERT INTO countries SET language_id=3, name="Italy", alternative_spellings="IT Italia", relevancy="5";
INSERT INTO countries SET language_id=3, name="Jamaica", alternative_spellings="JM";
INSERT INTO countries SET language_id=3, name="Japan", alternative_spellings="JP Nippon Nihon 日本", relevancy="2.5";
INSERT INTO countries SET language_id=3, name="Jersey", alternative_spellings="JE", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Jordan", alternative_spellings="JO الأردن";
INSERT INTO countries SET language_id=3, name="Kazakhstan", alternative_spellings="KZ Қазақстан Казахстан";
INSERT INTO countries SET language_id=3, name="Kenya", alternative_spellings="KE";
INSERT INTO countries SET language_id=3, name="Kiribati", alternative_spellings="KI";
INSERT INTO countries SET language_id=3, name="Korea, Democratic People\'s Republic of", alternative_spellings="KP North Korea";
INSERT INTO countries SET language_id=3, name="Korea, Republic of", alternative_spellings="KR South Korea", relevancy="1.5";
INSERT INTO countries SET language_id=3, name="Kuwait", alternative_spellings="KW الكويت";
INSERT INTO countries SET language_id=3, name="Kyrgyzstan", alternative_spellings="KG Кыргызстан";
INSERT INTO countries SET language_id=3, name="Lao People\'s Democratic Republic", alternative_spellings="LA";
INSERT INTO countries SET language_id=3, name="Latvia", alternative_spellings="LV Latvija";
INSERT INTO countries SET language_id=3, name="Lebanon", alternative_spellings="LB لبنان";
INSERT INTO countries SET language_id=3, name="Lesotho", alternative_spellings="LS";
INSERT INTO countries SET language_id=3, name="Liberia", alternative_spellings="LR";
INSERT INTO countries SET language_id=3, name="Libyan Arab Jamahiriya", alternative_spellings="LY ليبيا";
INSERT INTO countries SET language_id=3, name="Liechtenstein", alternative_spellings="LI";
INSERT INTO countries SET language_id=3, name="Lithuania", alternative_spellings="LT Lietuva";
INSERT INTO countries SET language_id=3, name="Luxembourg", alternative_spellings="LU";
INSERT INTO countries SET language_id=3, name="Macao", alternative_spellings="MO";
INSERT INTO countries SET language_id=3, name="Macedonia, The Former Yugoslav Republic Of", alternative_spellings="MK Македонија";
INSERT INTO countries SET language_id=3, name="Madagascar", alternative_spellings="MG Madagasikara";
INSERT INTO countries SET language_id=3, name="Malawi", alternative_spellings="MW";
INSERT INTO countries SET language_id=3, name="Malaysia", alternative_spellings="MY";
INSERT INTO countries SET language_id=3, name="Maldives", alternative_spellings="MV";
INSERT INTO countries SET language_id=3, name="Mali", alternative_spellings="ML";
INSERT INTO countries SET language_id=3, name="Malta", alternative_spellings="MT";
INSERT INTO countries SET language_id=3, name="Marshall Islands", alternative_spellings="MH", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Martinique", alternative_spellings="MQ";
INSERT INTO countries SET language_id=3, name="Mauritania", alternative_spellings="MR الموريتانية";
INSERT INTO countries SET language_id=3, name="Mauritius", alternative_spellings="MU";
INSERT INTO countries SET language_id=3, name="Mayotte", alternative_spellings="YT";
INSERT INTO countries SET language_id=3, name="Mexico", alternative_spellings="MX Mexicanos", relevancy="1.5";
INSERT INTO countries SET language_id=3, name="Micronesia, Federated States of", alternative_spellings="FM";
INSERT INTO countries SET language_id=3, name="Moldova, Republic of", alternative_spellings="MD";
INSERT INTO countries SET language_id=3, name="Monaco", alternative_spellings="MC";
INSERT INTO countries SET language_id=3, name="Mongolia", alternative_spellings="MN Mongγol ulus Монгол улс";
INSERT INTO countries SET language_id=3, name="Montenegro", alternative_spellings="ME";
INSERT INTO countries SET language_id=3, name="Montserrat", alternative_spellings="MS", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Morocco", alternative_spellings="MA المغرب";
INSERT INTO countries SET language_id=3, name="Mozambique", alternative_spellings="MZ Moçambique";
INSERT INTO countries SET language_id=3, name="Myanmar", alternative_spellings="MM";
INSERT INTO countries SET language_id=3, name="Namibia", alternative_spellings="NA Namibië";
INSERT INTO countries SET language_id=3, name="Nauru", alternative_spellings="NR Naoero", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Nepal", alternative_spellings="NP नेपाल";
INSERT INTO countries SET language_id=3, name="Netherlands", alternative_spellings="NL Holland Nederland", relevancy="5";
INSERT INTO countries SET language_id=3, name="New Caledonia", alternative_spellings="NC", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="New Zealand", alternative_spellings="NZ Aotearoa";
INSERT INTO countries SET language_id=3, name="Nicaragua", alternative_spellings="NI";
INSERT INTO countries SET language_id=3, name="Niger", alternative_spellings="NE Nijar";
INSERT INTO countries SET language_id=3, name="Nigeria", alternative_spellings="NG Nijeriya Naíjíríà", relevancy="1.5";
INSERT INTO countries SET language_id=3, name="Niue", alternative_spellings="NU", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Norfolk Island", alternative_spellings="NF", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Northern Mariana Islands", alternative_spellings="MP", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Norway", alternative_spellings="NO Norge Noreg", relevancy="5";
INSERT INTO countries SET language_id=3, name="Oman", alternative_spellings="OM عمان";
INSERT INTO countries SET language_id=3, name="Pakistan", alternative_spellings="PK پاکستان", relevancy="2";
INSERT INTO countries SET language_id=3, name="Palau", alternative_spellings="PW", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Palestinian Territory, Occupied", alternative_spellings="PS فلسطين";
INSERT INTO countries SET language_id=3, name="Panama", alternative_spellings="PA";
INSERT INTO countries SET language_id=3, name="Papua New Guinea", alternative_spellings="PG";
INSERT INTO countries SET language_id=3, name="Paraguay", alternative_spellings="PY";
INSERT INTO countries SET language_id=3, name="Peru", alternative_spellings="PE";
INSERT INTO countries SET language_id=3, name="Philippines", alternative_spellings="PH Pilipinas", relevancy="1.5";
INSERT INTO countries SET language_id=3, name="Pitcairn", alternative_spellings="PN", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Poland", alternative_spellings="PL Polska", relevancy="3";
INSERT INTO countries SET language_id=3, name="Portugal", alternative_spellings="PT Portuguesa", relevancy="1.5";
INSERT INTO countries SET language_id=3, name="Puerto Rico", alternative_spellings="PR";
INSERT INTO countries SET language_id=3, name="Qatar", alternative_spellings="QA قطر";
INSERT INTO countries SET language_id=3, name="Réunion", alternative_spellings="RE Reunion";
INSERT INTO countries SET language_id=3, name="Romania", alternative_spellings="RO Rumania Roumania România";
INSERT INTO countries SET language_id=3, name="Russian Federation", alternative_spellings="RU Rossiya Российская Россия", relevancy="2.5";
INSERT INTO countries SET language_id=3, name="Rwanda", alternative_spellings="RW";
INSERT INTO countries SET language_id=3, name="Saint Barthélemy", alternative_spellings="BL St. Barthelemy";
INSERT INTO countries SET language_id=3, name="Saint Helena", alternative_spellings="SH St.";
INSERT INTO countries SET language_id=3, name="Saint Kitts and Nevis", alternative_spellings="KN St.";
INSERT INTO countries SET language_id=3, name="Saint Lucia", alternative_spellings="LC St.";
INSERT INTO countries SET language_id=3, name="Saint Martin (French Part)", alternative_spellings="MF St.";
INSERT INTO countries SET language_id=3, name="Saint Pierre and Miquelon", alternative_spellings="PM St.";
INSERT INTO countries SET language_id=3, name="Saint Vincent and the Grenadines", alternative_spellings="VC St.";
INSERT INTO countries SET language_id=3, name="Samoa", alternative_spellings="WS";
INSERT INTO countries SET language_id=3, name="San Marino", alternative_spellings="SM";
INSERT INTO countries SET language_id=3, name="Sao Tome and Principe", alternative_spellings="ST";
INSERT INTO countries SET language_id=3, name="Saudi Arabia", alternative_spellings="SA السعودية";
INSERT INTO countries SET language_id=3, name="Senegal", alternative_spellings="SN Sénégal";
INSERT INTO countries SET language_id=3, name="Serbia", alternative_spellings="RS Србија Srbija";
INSERT INTO countries SET language_id=3, name="Seychelles", alternative_spellings="SC", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Sierra Leone", alternative_spellings="SL";
INSERT INTO countries SET language_id=3, name="Singapore", alternative_spellings="SG Singapura  சிங்கப்பூர் குடியரசு 新加坡共和国";
INSERT INTO countries SET language_id=3, name="Sint Maarten (Dutch Part)", alternative_spellings="SX";
INSERT INTO countries SET language_id=3, name="Slovakia", alternative_spellings="SK Slovenská Slovensko";
INSERT INTO countries SET language_id=3, name="Slovenia", alternative_spellings="SI Slovenija";
INSERT INTO countries SET language_id=3, name="Solomon Islands", alternative_spellings="SB";
INSERT INTO countries SET language_id=3, name="Somalia", alternative_spellings="SO الصومال";
INSERT INTO countries SET language_id=3, name="South Africa", alternative_spellings="ZA RSA Suid-Afrika";
INSERT INTO countries SET language_id=3, name="South Georgia and the South Sandwich Islands", alternative_spellings="GS";
INSERT INTO countries SET language_id=3, name="South Sudan", alternative_spellings="SS";
INSERT INTO countries SET language_id=3, name="Spain", alternative_spellings="ES España", relevancy="5";
INSERT INTO countries SET language_id=3, name="Sri Lanka", alternative_spellings="LK ශ්‍රී ලංකා இலங்கை Ceylon";
INSERT INTO countries SET language_id=3, name="Sudan", alternative_spellings="SD السودان";
INSERT INTO countries SET language_id=3, name="Suriname", alternative_spellings="SR शर्नम् Sarnam Sranangron";
INSERT INTO countries SET language_id=3, name="Svalbard and Jan Mayen", alternative_spellings="SJ", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Swaziland", alternative_spellings="SZ weSwatini Swatini Ngwane";
INSERT INTO countries SET language_id=3, name="Sweden", alternative_spellings="SE Sverige", relevancy="3";
INSERT INTO countries SET language_id=3, name="Switzerland", alternative_spellings="CH Swiss Confederation Schweiz Suisse Svizzera Svizra", relevancy="1.5";
INSERT INTO countries SET language_id=3, name="Syrian Arab Republic", alternative_spellings="SY Syria سورية";
INSERT INTO countries SET language_id=3, name="Taiwan, Province of China", alternative_spellings="TW 台灣 臺灣";
INSERT INTO countries SET language_id=3, name="Tajikistan", alternative_spellings="TJ Тоҷикистон Toçikiston";
INSERT INTO countries SET language_id=3, name="Tanzania, United Republic of", alternative_spellings="TZ";
INSERT INTO countries SET language_id=3, name="Thailand", alternative_spellings="TH ประเทศไทย Prathet Thai";
INSERT INTO countries SET language_id=3, name="Timor-Leste", alternative_spellings="TL";
INSERT INTO countries SET language_id=3, name="Togo", alternative_spellings="TG Togolese";
INSERT INTO countries SET language_id=3, name="Tokelau", alternative_spellings="TK", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Tonga", alternative_spellings="TO";
INSERT INTO countries SET language_id=3, name="Trinidad and Tobago", alternative_spellings="TT";
INSERT INTO countries SET language_id=3, name="Tunisia", alternative_spellings="TN تونس";
INSERT INTO countries SET language_id=3, name="Turkey", alternative_spellings="TR Türkiye Turkiye";
INSERT INTO countries SET language_id=3, name="Turkmenistan", alternative_spellings="TM Türkmenistan";
INSERT INTO countries SET language_id=3, name="Turks and Caicos Islands", alternative_spellings="TC", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Tuvalu", alternative_spellings="TV", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Uganda", alternative_spellings="UG";
INSERT INTO countries SET language_id=3, name="Ukraine", alternative_spellings="UA Ukrayina Україна";
INSERT INTO countries SET language_id=3, name="United Arab Emirates", alternative_spellings="AE UAE الإمارات";
INSERT INTO countries SET language_id=3, name="United Kingdom", alternative_spellings="GB Great Britain England UK Wales Scotland Northern Ireland", relevancy="5";
INSERT INTO countries SET language_id=3, name="United States", relevancy="5", alternative_spellings="US USA United States of America";
INSERT INTO countries SET language_id=3, name="United States Minor Outlying Islands", alternative_spellings="UM";
INSERT INTO countries SET language_id=3, name="Uruguay", alternative_spellings="UY";
INSERT INTO countries SET language_id=3, name="Uzbekistan", alternative_spellings="UZ Ўзбекистон O\'zbekstan O‘zbekiston";
INSERT INTO countries SET language_id=3, name="Vanuatu", alternative_spellings="VU";
INSERT INTO countries SET language_id=3, name="Venezuela", alternative_spellings="VE";
INSERT INTO countries SET language_id=3, name="Vietnam", alternative_spellings="VN Việt Nam", relevancy="1.5";
INSERT INTO countries SET language_id=3, name="Virgin Islands, British", alternative_spellings="VG", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Virgin Islands, U.S.", alternative_spellings="VI", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Wallis and Futuna", alternative_spellings="WF", relevancy="0.5";
INSERT INTO countries SET language_id=3, name="Western Sahara", alternative_spellings="EH لصحراء الغربية";
INSERT INTO countries SET language_id=3, name="Yemen", alternative_spellings="YE اليمن";
INSERT INTO countries SET language_id=3, name="Zambia", alternative_spellings="ZM";
INSERT INTO countries SET language_id=3, name="Zimbabwe", alternative_spellings="ZW";
